version: "3"

services:
  api-gateway:
    build:
      context: "."
    networks:
      - "frontend"
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./dist:/usr/share/api-gateway/dist
    environment:
      NODE_ENV: "test"
      GRAPHQL_PORT: "3000"
      JWT_ACCESSTOKEN_SECRET: "VtWeuJo5cPrH1gzvLX0HwPkcbVVeMkV0/a2JFeP3hGE="
      JWT_REFRESHTOKEN_SECRET: "tPQz6vb7nJDilma85OQExilvgZX+QyEf1CL95DmfBLA="
      JWT_ISSUER: "application"
      JWT_AUDIENCE: "public"
      COMMENTS_SVC_URL: "comments-svc:50051"
      POSTS_SVC_URL: "posts-svc:50051"
      USERS_SVC_URL: "users-svc:50051"
      MAILER_SVC_URL: "mailer-svc:50051"
      REDIS_HOST: "cache"
      REDIS_PORT: "6379"
    healthcheck:
      test: ["CMD", "wget", "localhost:3000/healthz -q -O - > /dev/null 2>&1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: "on-failure"
networks:
  frontend:
