version: "3"

services:

  mailer-svc:
    build:
      context: "."
    networks:
      - "mailer-svc"
    ports:
      - "10002:50051"
    environment:
      NODE_ENV: "test"
      GRPC_HOST: "0.0.0.0"
      GRPC_PORT: "50051"
      SMTP_HOST: "smtp.qq.com"
      SMTP_PORT: "465"
      SMTP_SECURE: "true"
      SMTP_USER: "1378026744@qq.com"
      SMTP_PASS: "0216zp"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: "on-failure"

networks:
  mailer-svc:
