version: "3"
services:
  cache:
    image: "redis:5-alpine"
    container_name: "public-dev-cache"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'redis-cli PING'"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: "on-failure"
