version: "3"
services:
  db:
    image: "postgres:12-alpine"
    container_name: "posts-dev-db"
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres'"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: "on-failure"
